/**
 * bean-counter — infrastructure skeleton.
 *
 * ┌──────────────────────────────────────────────────────────────────────────────┐
 * │ THIS STACK HAS NEVER BEEN DEPLOYED AND HAS NOT BEEN SECURITY REVIEWED.        │
 * │ It exists to describe the shape the application would need, not to be run.    │
 * │ Read infra/README.md — especially the cost section — before doing anything.   │
 * └──────────────────────────────────────────────────────────────────────────────┘
 *
 * The shape, top to bottom:
 *
 *   Internet ──> CloudFront ──> S3 (private)              the React stock board, static files
 *            └─> ALB (public subnets)
 *                  └─> Fargate service (private subnets)  the Node API
 *                        └─> RDS Postgres (isolated)      the event log — the system of record
 *
 * Three deliberate boundaries, each one load-bearing:
 *   1. The database sits in ISOLATED subnets. It has no route to the internet in either
 *      direction and is reachable only from the API's security group.
 *   2. The API runs in PRIVATE subnets. Inbound traffic arrives only through the ALB.
 *   3. The S3 bucket is fully private. CloudFront reaches it through Origin Access Control;
 *      nothing else can.
 */
import * as path from 'node:path';
import * as cdk from 'aws-cdk-lib';
import * as cloudfront from 'aws-cdk-lib/aws-cloudfront';
import * as origins from 'aws-cdk-lib/aws-cloudfront-origins';
import * as ec2 from 'aws-cdk-lib/aws-ec2';
import * as ecs from 'aws-cdk-lib/aws-ecs';
import * as ecsPatterns from 'aws-cdk-lib/aws-ecs-patterns';
import * as rds from 'aws-cdk-lib/aws-rds';
import * as s3 from 'aws-cdk-lib/aws-s3';
import { Construct } from 'constructs';

/** Repo root — npm workspaces need the root lockfile as build context. See backend/Dockerfile. */
const REPO_ROOT = path.join(__dirname, '..', '..');

export class BeanCounterStack extends cdk.Stack {
  constructor(scope: Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    // ── The deploy gate ───────────────────────────────────────────────────────────
    // A CloudFormation parameter with no default. `cdk synth` is unaffected, but
    // `cdk deploy` cannot proceed unless someone explicitly passes this value — so a
    // deploy is always a deliberate act and never a slip of the shell history.
    //
    // This is a guardrail expressed as structure rather than as a sentence in a README,
    // because a README cannot stop a command.
    const acknowledgement = new cdk.CfnParameter(this, 'AcknowledgeNotProductionReady', {
      type: 'String',
      description:
        'Type "I have read infra/README.md and had this reviewed" to deploy. This stack has not ' +
        'been security reviewed and provisions billable resources (RDS, NAT gateway, ALB).',
      allowedValues: ['I have read infra/README.md and had this reviewed'],
      noEcho: false,
    });
    // Referenced so CloudFormation cannot optimise the parameter away.
    new cdk.CfnOutput(this, 'DeploymentAcknowledgement', { value: acknowledgement.valueAsString });

    // ── Network ───────────────────────────────────────────────────────────────────
    // Two AZs is the minimum for an ALB and for RDS to be able to fail over later.
    //
    // COST: `natGateways` is the expensive dial here. Each NAT gateway is billed hourly
    // whether or not traffic flows through it, and it is the line item that surprises
    // people. One is enough for a skeleton; production would want one per AZ for
    // availability, at roughly double the cost.
    const vpc = new ec2.Vpc(this, 'Vpc', {
      maxAzs: 2,
      natGateways: 1,
      subnetConfiguration: [
        { name: 'public', subnetType: ec2.SubnetType.PUBLIC, cidrMask: 24 },
        { name: 'private', subnetType: ec2.SubnetType.PRIVATE_WITH_EGRESS, cidrMask: 24 },
        // The database lives here: no NAT, no internet gateway, no egress at all.
        { name: 'isolated', subnetType: ec2.SubnetType.PRIVATE_ISOLATED, cidrMask: 24 },
      ],
    });

    // ── Database: the event log ───────────────────────────────────────────────────
    // This holds the append-only `events` table, which is the system of record for the
    // whole application. Everything else in this stack is replaceable; this is not.
    const database = new rds.DatabaseInstance(this, 'Database', {
      engine: rds.DatabaseInstanceEngine.postgres({
        version: rds.PostgresEngineVersion.VER_16_4,
      }),
      // Matches the local docker-compose database, so the same migrations apply.
      instanceType: ec2.InstanceType.of(ec2.InstanceClass.T4G, ec2.InstanceSize.MICRO),
      vpc,
      vpcSubnets: { subnetType: ec2.SubnetType.PRIVATE_ISOLATED },
      // Never publicly reachable. Access is via the API's security group only.
      publiclyAccessible: false,
      // The password is generated by Secrets Manager and never appears in this repo,
      // in a template, or in an environment variable committed anywhere.
      credentials: rds.Credentials.fromGeneratedSecret('beancounter'),
      databaseName: 'bean_counter',
      storageEncrypted: true,
      backupRetention: cdk.Duration.days(7),
      deletionProtection: true,
      // RETAIN, deliberately. `cdk destroy` will NOT delete the event log — losing the
      // log means losing every fact the system knows, and no convenience is worth that.
      // The trade-off is that a retained instance keeps billing after a destroy; the
      // README says so explicitly, because that is the surprise worth warning about.
      removalPolicy: cdk.RemovalPolicy.RETAIN,
    });

    // ── API: the Node backend ─────────────────────────────────────────────────────
    const cluster = new ecs.Cluster(this, 'Cluster', { vpc, containerInsightsV2: ecs.ContainerInsights.ENABLED });

    // COST: the ALB is billed hourly, like the NAT gateway, independent of traffic.
    const api = new ecsPatterns.ApplicationLoadBalancedFargateService(this, 'Api', {
      cluster,
      cpu: 256,
      memoryLimitMiB: 512,
      desiredCount: 1,
      publicLoadBalancer: true,
      // A failing deployment rolls itself back instead of grinding on for hours.
      circuitBreaker: { rollback: true },
      // Do not drop below the desired count mid-deployment. With one task that means a
      // brief second task rather than a gap in service.
      minHealthyPercent: 100,
      taskSubnets: { subnetType: ec2.SubnetType.PRIVATE_WITH_EGRESS },
      taskImageOptions: {
        // Built from backend/Dockerfile, context = repo root (npm workspaces need the
        // root lockfile). `cdk synth`/`cdk deploy` run this build locally via Docker;
        // CDK pushes the result to its bootstrap ECR asset repository.
        image: ecs.ContainerImage.fromAsset(REPO_ROOT, { file: 'backend/Dockerfile' }),
        containerPort: 3000,
        environment: {
          NODE_ENV: 'production',
          PORT: '3000',
        },
        secrets: {
          // Injected at runtime from Secrets Manager. The credential is never baked into
          // the image, the task definition, or this repository.
          DATABASE_SECRET: ecs.Secret.fromSecretsManager(database.secret!),
        },
      },
    });

    // The only path to the database: this security group, this port. Not the VPC CIDR,
    // not a wide-open ingress rule.
    database.connections.allowDefaultPortFrom(api.service, 'API tasks reach Postgres');

    api.targetGroup.configureHealthCheck({
      path: '/api/health',
      healthyHttpCodes: '200',
    });

    // ── Frontend: the stock board ─────────────────────────────────────────────────
    // Static Vite build output. The bucket is private; CloudFront is the only reader.
    const siteBucket = new s3.Bucket(this, 'SiteBucket', {
      blockPublicAccess: s3.BlockPublicAccess.BLOCK_ALL,
      encryption: s3.BucketEncryption.S3_MANAGED,
      enforceSSL: true,
      versioned: true,
      // Safe to remove: these are build artifacts, reproducible from source. Contrast
      // with the database above, which is not.
      removalPolicy: cdk.RemovalPolicy.DESTROY,
      autoDeleteObjects: true,
    });

    const distribution = new cloudfront.Distribution(this, 'SiteDistribution', {
      defaultBehavior: {
        // Origin Access Control — CloudFront signs its requests to S3, so the bucket
        // policy can refuse everyone else.
        origin: origins.S3BucketOrigin.withOriginAccessControl(siteBucket),
        viewerProtocolPolicy: cloudfront.ViewerProtocolPolicy.REDIRECT_TO_HTTPS,
      },
      defaultRootObject: 'index.html',
      errorResponses: [
        // Single-page app: unknown paths are client-side routes, not missing files.
        { httpStatus: 403, responseHttpStatus: 200, responsePagePath: '/index.html' },
        { httpStatus: 404, responseHttpStatus: 200, responsePagePath: '/index.html' },
      ],
    });

    new cdk.CfnOutput(this, 'ApiUrl', {
      value: `http://${api.loadBalancer.loadBalancerDnsName}`,
      description: 'API load balancer DNS name (HTTP only — TLS is an unresolved gap, see README)',
    });
    new cdk.CfnOutput(this, 'SiteUrl', {
      value: `https://${distribution.distributionDomainName}`,
      description: 'CloudFront domain for the stock board',
    });
    new cdk.CfnOutput(this, 'DatabaseSecretArn', {
      value: database.secret!.secretArn,
      description: 'Secrets Manager ARN holding the generated database credentials',
    });
  }
}
