import { useRef, useState } from 'react';
import { ApiError, EVENT_ID_CONFLICT, postEvent } from '../lib/api.ts';
import type { NewEvent, StockItem } from '../lib/types.ts';
import { INPUT_UNITS, parseQuantity } from '../lib/units.ts';

type Kind = 'receive' | 'waste';

interface Props {
  kind: Kind;
  items: StockItem[];
  /** Called after a successful append, so the board and ledger re-read. */
  onRecorded: () => void;
}

const COPY: Record<Kind, { title: string; submit: string; done: string; replayed: string }> = {
  receive: {
    title: 'Receive stock',
    submit: 'Record delivery',
    done: 'Delivery recorded.',
    replayed: 'Already recorded — this delivery is in the log once, not twice.',
  },
  waste: {
    title: 'Record waste',
    submit: 'Record waste',
    done: 'Waste recorded.',
    replayed: 'Already recorded — this waste is in the log once, not twice.',
  },
};

/**
 * Receive-stock and record-waste share every field but the supplier, so they
 * share a form. The quantity leaves here as an integer in the item's base unit
 * — `parseQuantity` is the only thing that converts.
 *
 * The log is append-only, so a double-press must not become a double delivery:
 * every send carries an `eventId` the backend dedupes on. See `pending` below
 * for the lifecycle that makes it stable across retries.
 */
export function MovementForm({ kind, items, onRecorded }: Props) {
  const [itemId, setItemId] = useState('');
  const [amount, setAmount] = useState('');
  const [unitLabel, setUnitLabel] = useState('');
  const [supplier, setSupplier] = useState('');
  const [error, setError] = useState<string | null>(null);
  const [notice, setNotice] = useState<string | null>(null);
  const [busy, setBusy] = useState(false);
  const [canRetry, setCanRetry] = useState(false);

  /**
   * The idempotency handle for the submission the fields currently describe,
   * with the fact it was minted for.
   *
   * A ref, not state: it must survive re-renders without causing one, and it
   * must never be regenerated by a render or an effect. It is minted on send
   * when the fact differs from the one held, so a retry of the same submission
   * reuses it (the backend replays instead of appending a second delivery),
   * and edited fields get a fresh one instead of a false conflict. It is
   * cleared the moment the server confirms — the next genuinely-new entry must
   * not be mistaken for a replay of this one.
   */
  const pending = useRef<{ fact: string; eventId: string } | null>(null);

  const item = items.find((candidate) => candidate.itemId === itemId) ?? null;
  const units = item === null ? [] : INPUT_UNITS[item.baseUnit];
  const selectedUnit = units.find((u) => u.label === unitLabel)?.label ?? units[0]?.label ?? '';

  function selectItem(nextItemId: string) {
    setItemId(nextItemId);
    setUnitLabel(''); // fall back to the new item's own base unit
    setError(null);
    setCanRetry(false);
  }

  async function submit(event: React.FormEvent) {
    event.preventDefault();
    await send();
  }

  async function send() {
    setNotice(null);

    if (item === null) {
      setError('Pick an item.');
      setCanRetry(false);
      return;
    }

    const parsed = parseQuantity(amount, selectedUnit, item.baseUnit);
    if (!parsed.ok) {
      setError(parsed.error);
      setCanRetry(false);
      return;
    }

    const body: NewEvent =
      kind === 'receive'
        ? {
            type: 'StockReceived',
            itemId: item.itemId,
            quantity: parsed.quantity,
            ...(supplier.trim() === '' ? {} : { supplier: supplier.trim() }),
          }
        : { type: 'StockDepleted', itemId: item.itemId, quantity: parsed.quantity, reason: 'waste' };

    const fact = JSON.stringify(body);
    if (pending.current?.fact !== fact) {
      pending.current = { fact, eventId: crypto.randomUUID() };
    }

    setBusy(true);
    setError(null);
    setCanRetry(false);
    try {
      const appended = await postEvent(body, pending.current.eventId);
      pending.current = null; // spent: the next entry is a new fact, new handle
      setAmount('');
      setSupplier('');
      setNotice(appended.replayed ? COPY[kind].replayed : COPY[kind].done);
      onRecorded();
    } catch (err: unknown) {
      if (err instanceof ApiError && err.code === EVENT_ID_CONFLICT) {
        // The handle is already spent on a different fact. Sending it again can
        // only conflict again, and minting a new one would append the duplicate
        // the handle exists to prevent — so no retry, just the truth.
        setError(`${err.message} Refresh the board and check the log before recording this again.`);
      } else {
        setError(err instanceof ApiError ? err.message : 'Could not record that event.');
        setCanRetry(true); // same handle, so a retry cannot double the entry
      }
    } finally {
      setBusy(false);
    }
  }

  const fieldId = `${kind}-`;

  return (
    <form className="movement" aria-label={COPY[kind].title} onSubmit={submit}>
      <h2>{COPY[kind].title}</h2>

      <label htmlFor={`${fieldId}item`}>Item</label>
      <select
        id={`${fieldId}item`}
        value={itemId}
        onChange={(e) => selectItem(e.target.value)}
        disabled={items.length === 0}
      >
        <option value="">Choose an item…</option>
        {items.map((candidate) => (
          <option key={candidate.itemId} value={candidate.itemId}>
            {candidate.name}
          </option>
        ))}
      </select>

      <label htmlFor={`${fieldId}amount`}>Quantity</label>
      <div className="quantity">
        <input
          id={`${fieldId}amount`}
          inputMode="decimal"
          value={amount}
          onChange={(e) => setAmount(e.target.value)}
          placeholder="12"
        />
        <select
          aria-label="Unit"
          value={selectedUnit}
          onChange={(e) => setUnitLabel(e.target.value)}
          disabled={item === null}
        >
          {units.map((unit) => (
            <option key={unit.label} value={unit.label}>
              {unit.label}
            </option>
          ))}
        </select>
      </div>

      {kind === 'receive' && (
        <>
          <label htmlFor={`${fieldId}supplier`}>Supplier (optional)</label>
          <input
            id={`${fieldId}supplier`}
            value={supplier}
            onChange={(e) => setSupplier(e.target.value)}
          />
        </>
      )}

      <button type="submit" disabled={busy || items.length === 0}>
        {busy ? 'Recording…' : COPY[kind].submit}
      </button>

      {error !== null && (
        <p className="error" role="alert">
          {error}
        </p>
      )}
      {canRetry && (
        <button type="button" className="retry" onClick={() => void send()} disabled={busy}>
          Try again
        </button>
      )}
      {notice !== null && <p className="notice">{notice}</p>}
    </form>
  );
}
